version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - FRONTEND_ORIGINS=http://localhost:5173
    depends_on:
      - redis
    volumes:
      - ./backend/data:/app/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    stdin_open: true
    tty: true
